// Bundles the in-frame runtime (src/runtime) into one IIFE string that
// buildBootstrapHtml inlines into every widget frame. aui-build compiles
// modules one by one, so it cannot produce this single self-contained script.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "rolldown";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const output = resolve(root, "src/runtime/generated.ts");
const { version } = JSON.parse(
  readFileSync(resolve(root, "package.json"), "utf8"),
);

const result = await build({
  input: resolve(root, "scripts/runtime-entry.ts"),
  platform: "browser",
  write: false,
  transform: { define: { __AUI_PACKAGE_VERSION__: JSON.stringify(version) } },
  output: { format: "iife", minify: true },
});

const code = result.output[0].code.trim();
const banner =
  "// Generated by scripts/build-runtime.mjs from src/runtime. Do not edit by hand.\n";
const next = `${banner}export const runtimeSource: string = ${JSON.stringify(code)};\n`;

let previous;
try {
  previous = readFileSync(output, "utf8");
} catch {}
if (previous !== next) writeFileSync(output, next);
console.log(`runtime: ${code.length} bytes`);
