declare module "*.css";

// Generated by the glob-modules plugin in scripts/build.mts: the default export
// of every file in the folder, sorted by file name.
declare module "virtual:rich-fixtures" {
  const modules: readonly {
    file: string;
    value: readonly import("../src/fixtures/types").Fixture[];
  }[];
  export default modules;
}

declare module "virtual:fixture-uis" {
  const modules: readonly {
    file: string;
    value: import("./define-fixture-ui").FixtureUI;
  }[];
  export default modules;
}
