packages:
  - packages/*
  - examples/*
  - examples/with-openai-apps/servers
  - examples/with-openai-apps/client
  - apps/*

onlyBuiltDependencies:
  - '@tailwindcss/oxide@4.1.17'
  - esbuild
  - sharp@0.34.5
  - unrs-resolver@1.11.1

strictDepBuilds: true

verifyDepsBeforeRun: true
