#!/usr/bin/env node
// Regenerates src/internal/version.ts from package.json so the runtime
// duplicate-detection check reports the exact version that was published.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = resolve(here, "..", "package.json");
const outPath = resolve(here, "..", "src", "internal", "version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const contents =
  `// This file is generated by scripts/sync-version.mjs and kept in sync\n` +
  `// with package.json#version on \`prebuild\` and \`pretest\`.\n` +
  `export const PACKAGE_VERSION = ${JSON.stringify(pkg.version)};\n`;

const existing = (() => {
  try {
    return readFileSync(outPath, "utf8");
  } catch {
    return null;
  }
})();

if (existing !== contents) {
  writeFileSync(outPath, contents);
}
