import "server-only";

export const HARNESS_SDK_AGENT_PROMPTS = new Map<string, string>([
  [
    "harness-sdk",
    `Build the shared AI chat application described in the user's setup instructions with the alpha harness-sdk runtime, assistant-ui, and Assistant Cloud. Preserve the existing requirements and setup notes. If the brief is missing, ask what they want to build before proposing a plan; in a setup session use \`ask "What AI chat do you want to build with harness-sdk?" --wait\`.

Read https://www.assistant-ui.com/harness-sdk.md. Use the verified CLI preview at https://www.assistant-ui.com/downloads/assistant-ui-cloud-harness-b9d8b56ad.tgz, not an assumed published cloud setup command or an invented adapter release. The preview bundles official-source harness-sdk 0.3.1, @assistant-ui/react-harness-sdk 0.0.2 and Statewire 0.19.3 archives at revision 3d3a180f0400b84267f62969d42f8b102bed4479, with required peers for the shared core/store/tap runtime. Retain its vendor archives and provenance.

1. Inspect the selected project, package manager, framework, existing chat UI, authentication and server routes. Ask which project or folder to use before creating anything. The CLI creates a new Next.js cloud-harness app and refuses to overwrite an existing app. For a new app, use the folder the user chose. For an existing app, use an agreed temporary scaffold and adapt its runtime, credentials and backend route into the selected project; preserve that project's framework and UI. Do not replace an existing app with the scaffold or install into a folder the user did not choose.
2. Run \`npx --package=https://www.assistant-ui.com/downloads/assistant-ui-cloud-harness-b9d8b56ad.tgz assistant-ui cloud setup <chosen-new-directory> --use-npm --access-code MULTIPLAYER-2026\` for npm projects. Select --use-pnpm, --use-yarn or --use-bun when appropriate. In a non-interactive agent shell use --no-open so the user can open the printed device sign-in URL. Let the user authorize their account and select or create the organization/project; with --yes, supply their selected --org/--project or --new-org/--new-project flags rather than guessing resources.
3. The assistant-ui-cli public OAuth client is registered. Real device sign-in and production provisioning have passed; hosted shared-chat verification is still in progress. If sign-in or provisioning fails, report the exact error. Do not claim a working Cloud project, fabricate config, expose credentials, or change account-client permissions yourself. Local source preparation can proceed from the preview's bundled templates/cloud-harness files, but mark hosted verification pending until real authorization succeeds. Follow the CLI's resume instructions and keep the saved provisioning request ID; do not blindly retry provisioning into new folders.
4. After provisioning, keep ASSISTANT_API_KEY in server-only .env.local. NEXT_PUBLIC_ASSISTANT_BASE_URL, NEXT_PUBLIC_ASSISTANT_HARNESS_URL and NEXT_PUBLIC_ASSISTANT_WORKSPACE_ID come from the CLI response; never invent them. Preserve the .assistant-ui/cloud.json metadata and existing environment entries. The event code grants one harness only to the redeemed project; it is not a global free-plan change, and redemption ends at midnight Pacific after October 3, 2026.
5. Implement the user's application with HarnessCloudThreadList from the bundled @assistant-ui/react-harness-sdk adapter and AuiConfig/AuiProvider from @assistant-ui/react. Keep or adapt the existing Thread, Composer, Message and tool UI rather than replacing it unnecessarily. Connect the runtime to the canonical /api/chat route, the configured harness origin/workspace, a server-minted credential callback, and stable shared thread IDs. The starter carries a thread ID in the URL hash; preserve the same ID across clients sharing a conversation.
6. Adapt /api/credential to mint a scoped token through AssistantCloud.auth.tokens.create using the server API key. The starter's userId "hackathon" is a public-demo identity; for private or per-user data use the project's authenticated identity and appropriate workspace membership. Never send ASSISTANT_API_KEY or provider keys to the browser, and use no-store for credentials.
7. Configure the user's chosen model provider through their existing secret workflow. The starter uses OPENAI_API_KEY in .env.local; ask for that through the approved environment mechanism or preserve their existing provider setup. Implement the requested prompts and tools in the server's AI SDK /api/chat route. Do not fabricate a model response or treat a mock credential as a completed hosted setup.
8. During local development the provisioned harness allows localhost. For a deployed app, use the exact deployed HTTPS /api/chat URL with --backend-url when creating a new harness, or update the existing harness backend allowlist through the dashboard. Keep the CLI's saved backendUrl consistent and preserve other allowlist entries; do not widen the allowlist indiscriminately. Use the framework's existing route/proxy structure so the configured URL resolves to the real AI route.
9. Install with the project's package manager, build, typecheck and start the app. Open the same shared-thread URL in two independent browsers. Send from each, verify both see the same user messages and streamed assistant reply, then reload and confirm the conversation is retained. Verify the user's requested behavior, credential scoping, sharing and tools. If production setup fails, report local checks separately and leave hosted verification pending.

Report the local URL, implemented application behavior, shared-thread verification, and any remaining account or deployment step.`,
  ],
]);
