import { beforeEach, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ limit: vi.fn() }));
vi.mock("@/lib/rate-limit", async (importOriginal) => ({
  ...(await importOriginal()),
  checkDocsSearchRateLimit: mocks.limit,
}));
// The source is generated by the MDX compiler, which is not part of this test runner.
vi.mock("@/lib/search/corpus", () => ({
  searchablePages: () => [
    {
      url: "/docs/cloud",
      data: { title: "Assistant Cloud", description: "Persist chats" },
    },
  ],
}));
import { GET } from "./route";

beforeEach(() => {
  vi.stubEnv("JEV_KEY", "test-key");
  mocks.limit.mockResolvedValue(null);
});
afterEach(() => {
  vi.unstubAllGlobals();
  vi.unstubAllEnvs();
});
const request = (query: string, scope = "All") =>
  new Request(
    `https://www.assistant-ui.com/api/search/suggest?${new URLSearchParams({ query, scope })}`,
  );

it("validates query length and the scope before doing paid work", async () => {
  const fetcher = vi.fn();
  vi.stubGlobal("fetch", fetcher);
  expect((await GET(request("ab"))).status).toBe(400);
  expect((await GET(request("x".repeat(121)))).status).toBe(400);
  expect((await GET(request("save history", "Unknown"))).status).toBe(400);
  expect(fetcher).not.toHaveBeenCalled();
  expect(mocks.limit).not.toHaveBeenCalled();
});

it("disables only suggestions when no key is configured", async () => {
  vi.stubEnv("JEV_KEY", "");
  const response = await GET(request("save history"));
  expect(await response.json()).toEqual({ pages: [] });
  expect(response.headers.get("cache-control")).toBe("no-store");
  expect(mocks.limit).not.toHaveBeenCalled();
});

it("enforces rate limits before making a Jev request", async () => {
  const fetcher = vi.fn();
  vi.stubGlobal("fetch", fetcher);
  mocks.limit.mockResolvedValue(new Response("Limited", { status: 429 }));
  expect((await GET(request("save history"))).status).toBe(429);
  expect(fetcher).not.toHaveBeenCalled();
});

it("returns catalogue data rather than a URL invented by the model", async () => {
  vi.stubGlobal(
    "fetch",
    vi.fn().mockResolvedValue(
      Response.json({
        answers: {
          pages_0: {
            type: "choice",
            choice: "page_0",
            confidence: 1,
            probabilities: { page_0: 1 },
          },
        },
      }),
    ),
  );
  const response = await GET(request("save history"));
  expect(response.status).toBe(200);
  expect(await response.json()).toEqual({
    pages: [
      {
        url: "/docs/cloud",
        title: "Assistant Cloud",
        description: "Persist chats",
      },
    ],
  });
});
