import type { PreviewMetadata } from "./types.js";

export const PREVIEWS: Record<string, PreviewMetadata> = {
  "next-minimal": { status: "missing" },
  "next-default": {
    status: "live",
    url: "/examples-preview/ai-sdk",
    screenshot: "/screenshot/examples/ai-sdk.png",
  },
  "next-cloud": { status: "missing" },
  "next-cloud-clerk": { status: "missing" },
  "next-langgraph": { status: "missing" },
  "next-mcp": { status: "missing" },
  "butterbase-chat": { status: "missing" },
  "butterbase-auth-chat": { status: "missing" },
  "butterbase-rag-chat": { status: "missing" },
  "butterbase-integrations-chat": { status: "missing" },
  "butterbase-saas-chat": { status: "missing" },
  "next-ai-sdk-v6": {
    status: "live",
    url: "/examples-preview/ai-sdk",
    screenshot: "/screenshot/examples/ai-sdk.png",
  },
  "next-artifacts": {
    status: "live",
    url: "/examples-preview/artifacts",
    screenshot: "/screenshot/examples/artifacts.png",
  },
  "next-chain-of-thought": { status: "missing" },
  "next-external-store": { status: "missing" },
  "next-assistant-transport": { status: "missing" },
  "next-custom-thread-list": { status: "missing" },
  "next-parent-id-grouping": { status: "missing" },
  "next-react-hook-form": {
    status: "live",
    url: "/examples-preview/form-demo",
    screenshot: "/screenshot/examples/form-demo.png",
  },
  "next-langgraph-example": { status: "missing" },
  "next-ag-ui": { status: "missing" },
  "next-cloud-example": { status: "missing" },
  "next-elevenlabs-scribe": { status: "missing" },
  "next-elevenlabs-conversational": { status: "missing" },
  "next-ffmpeg": { status: "missing" },
  "next-google-adk": { status: "missing" },
  "next-interactables": { status: "missing" },
  "next-livekit": { status: "missing" },
  "with-expo": { status: "missing" },
  "react-router": { status: "missing" },
  tanstack: { status: "missing" },
};
