import type { Preset, BuilderConfig } from "./types";

export const PRESETS: Preset[] = [
  {
    id: "default",
    name: "Default",
    description: "Clean, modern design with all features enabled",
    config: {
      components: {
        attachments: true,
        branchPicker: true,
        editMessage: true,
        actionBar: {
          copy: true,
          reload: true,
          speak: false,
          feedback: false,
        },
        threadWelcome: true,
        suggestions: true,
        scrollToBottom: true,
        markdown: true,
        codeHighlightTheme: "vitesse",
        reasoning: false,
        followUpSuggestions: false,
        avatar: false,
        typingIndicator: "dot",
        loadingIndicator: "text",
        loadingText: "Thinking...",
      },
      styles: {
        theme: "light",
        accentColor: "#0ea5e9",
        borderRadius: "lg",
        maxWidth: "44rem",
        fontFamily: "system-ui",
        fontSize: "base",
        messageSpacing: "comfortable",
        userMessagePosition: "right",
        animations: true,
      },
    },
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    description: "Dark theme inspired by ChatGPT's interface",
    config: {
      components: {
        attachments: true,
        branchPicker: true,
        editMessage: true,
        actionBar: {
          copy: true,
          reload: true,
          speak: false,
          feedback: true,
        },
        threadWelcome: true,
        suggestions: false,
        scrollToBottom: false,
        markdown: true,
        codeHighlightTheme: "github",
        reasoning: false,
        followUpSuggestions: false,
        avatar: true,
        typingIndicator: "dot",
        loadingIndicator: "text",
        loadingText: "Thinking...",
      },
      styles: {
        theme: "dark",
        accentColor: "#ffffff",
        borderRadius: "full",
        maxWidth: "48rem",
        fontFamily: "system-ui",
        fontSize: "base",
        messageSpacing: "comfortable",
        userMessagePosition: "right",
        animations: true,
      },
    },
  },
  {
    id: "claude",
    name: "Claude",
    description: "Warm, elegant design inspired by Claude's interface",
    config: {
      components: {
        attachments: true,
        branchPicker: false,
        editMessage: true,
        actionBar: {
          copy: true,
          reload: true,
          speak: false,
          feedback: true,
        },
        threadWelcome: false,
        suggestions: false,
        scrollToBottom: false,
        markdown: true,
        codeHighlightTheme: "vitesse",
        reasoning: true,
        followUpSuggestions: false,
        avatar: true,
        typingIndicator: "dot",
        loadingIndicator: "text",
        loadingText: "Thinking...",
      },
      styles: {
        theme: "light",
        accentColor: "#ae5630",
        borderRadius: "lg",
        maxWidth: "48rem",
        fontFamily: "Georgia, serif",
        fontSize: "base",
        messageSpacing: "spacious",
        userMessagePosition: "right",
        animations: true,
      },
    },
  },
  {
    id: "perplexity",
    name: "Perplexity",
    description: "Search-focused design with prominent answers",
    config: {
      components: {
        attachments: true,
        branchPicker: true,
        editMessage: false,
        actionBar: {
          copy: true,
          reload: true,
          speak: false,
          feedback: false,
        },
        threadWelcome: true,
        suggestions: false,
        scrollToBottom: true,
        markdown: true,
        codeHighlightTheme: "tokyo-night",
        reasoning: false,
        followUpSuggestions: true,
        avatar: false,
        typingIndicator: "dot",
        loadingIndicator: "text",
        loadingText: "Thinking...",
      },
      styles: {
        theme: "dark",
        accentColor: "#22d3ee",
        borderRadius: "lg",
        maxWidth: "42rem",
        fontFamily: "system-ui",
        fontSize: "base",
        messageSpacing: "comfortable",
        userMessagePosition: "left",
        animations: true,
      },
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Stripped-down interface with only essential features",
    config: {
      components: {
        attachments: false,
        branchPicker: false,
        editMessage: false,
        actionBar: {
          copy: true,
          reload: false,
          speak: false,
          feedback: false,
        },
        threadWelcome: false,
        suggestions: false,
        scrollToBottom: false,
        markdown: true,
        codeHighlightTheme: "none",
        reasoning: false,
        followUpSuggestions: false,
        avatar: false,
        typingIndicator: "none",
        loadingIndicator: "text",
        loadingText: "Thinking...",
      },
      styles: {
        theme: "light",
        accentColor: "#171717",
        borderRadius: "md",
        maxWidth: "40rem",
        fontFamily: "system-ui",
        fontSize: "base",
        messageSpacing: "compact",
        userMessagePosition: "right",
        animations: false,
      },
    },
  },
  {
    id: "gemini",
    name: "Gemini",
    description: "Google's Gemini-inspired clean interface",
    config: {
      components: {
        attachments: true,
        branchPicker: false,
        editMessage: true,
        actionBar: {
          copy: true,
          reload: true,
          speak: true,
          feedback: true,
        },
        threadWelcome: true,
        suggestions: true,
        scrollToBottom: true,
        markdown: true,
        codeHighlightTheme: "vitesse",
        reasoning: false,
        followUpSuggestions: true,
        avatar: false,
        typingIndicator: "dot",
        loadingIndicator: "text",
        loadingText: "Thinking...",
      },
      styles: {
        theme: "light",
        accentColor: "#6366f1",
        borderRadius: "full",
        maxWidth: "44rem",
        fontFamily: "system-ui",
        fontSize: "base",
        messageSpacing: "comfortable",
        userMessagePosition: "right",
        animations: true,
      },
    },
  },
  {
    id: "copilot",
    name: "Copilot",
    description: "GitHub Copilot inspired developer chat",
    config: {
      components: {
        attachments: true,
        branchPicker: true,
        editMessage: true,
        actionBar: {
          copy: true,
          reload: true,
          speak: false,
          feedback: true,
        },
        threadWelcome: true,
        suggestions: true,
        scrollToBottom: true,
        markdown: true,
        codeHighlightTheme: "one-dark-pro",
        reasoning: true,
        followUpSuggestions: false,
        avatar: true,
        typingIndicator: "dot",
        loadingIndicator: "text",
        loadingText: "Thinking...",
      },
      styles: {
        theme: "dark",
        accentColor: "#8b5cf6",
        borderRadius: "lg",
        maxWidth: "56rem",
        fontFamily: "ui-monospace, monospace",
        fontSize: "sm",
        messageSpacing: "compact",
        userMessagePosition: "right",
        animations: true,
      },
    },
  },
  {
    id: "slack",
    name: "Slack",
    description: "Team chat inspired collaborative interface",
    config: {
      components: {
        attachments: true,
        branchPicker: false,
        editMessage: true,
        actionBar: {
          copy: true,
          reload: false,
          speak: false,
          feedback: true,
        },
        threadWelcome: false,
        suggestions: false,
        scrollToBottom: true,
        markdown: true,
        codeHighlightTheme: "vitesse",
        reasoning: false,
        followUpSuggestions: false,
        avatar: true,
        typingIndicator: "dot",
        loadingIndicator: "text",
        loadingText: "Thinking...",
      },
      styles: {
        theme: "light",
        accentColor: "#10b981",
        borderRadius: "sm",
        maxWidth: "100%",
        fontFamily: "system-ui",
        fontSize: "base",
        messageSpacing: "compact",
        userMessagePosition: "left",
        animations: false,
      },
    },
  },
  {
    id: "grok",
    name: "Grok",
    description: "xAI's Grok-inspired minimal dark interface",
    config: {
      components: {
        attachments: true,
        branchPicker: false,
        editMessage: true,
        actionBar: {
          copy: true,
          reload: true,
          speak: false,
          feedback: true,
        },
        threadWelcome: false,
        suggestions: false,
        scrollToBottom: false,
        markdown: true,
        codeHighlightTheme: "dracula",
        reasoning: false,
        followUpSuggestions: false,
        avatar: false,
        typingIndicator: "dot",
        loadingIndicator: "text",
        loadingText: "Thinking...",
      },
      styles: {
        theme: "dark",
        accentColor: "#171717",
        borderRadius: "full",
        maxWidth: "48rem",
        fontFamily: "system-ui",
        fontSize: "base",
        messageSpacing: "comfortable",
        userMessagePosition: "right",
        animations: true,
      },
    },
  },
];

export function getPresetById(id: string): Preset | undefined {
  return PRESETS.find((preset) => preset.id === id);
}

export function configMatchesPreset(config: BuilderConfig): Preset | undefined {
  return PRESETS.find(
    (preset) => JSON.stringify(preset.config) === JSON.stringify(config),
  );
}
